### ISSUE TITLE
Data for 2019 or years going forward?

### ISSUE THREAD

**Issue by jeffcsauer** [ecmwf/caliver#17]
Hi all, 

`caliver` is a wonderful package! It is proving extremely helpful for some projects. 

I was wondering - is there any intent of the authors to provide 2019, 2020, or ongoing data? Or is `caliver` specifically for the original 1980–2018 study period?

Thank you so much!

**Comment by cvitolo** [comment]
Hi @jeffcsauer, thanks for the nice words!

`caliver` can be used for any fire danger data, not only for the original study period.

Fire danger reanalysis data are now available at higher resolution (based on ERA5) few days behind real-time, see this paper: https://www.nature.com/articles/s41597-020-0554-z

Data are available on the Copernicus Climate Data Store (CDS):
https://cds.climate.copernicus.eu/cdsapp#!/dataset/cems-fire-historical?tab=overview

The Fire Weather Index from 1980 to 2019 (June) is also available on Zenodo: https://zenodo.org/record/3269270
