### ISSUE TITLE
get_gfed4() does not run in RStudio, only in terminal

### ISSUE THREAD

**Issue by cvitolo** [ecmwf/caliver#4]
When I try to run the following test in RStudio, the process gets stuck

    MonthlyBurnedAreas <- get_gfed4(start_date = "2003-01-01",  
                                    end_date = "2003-01-31",
                                    temporal_resolution = "monthly", 
                                    varname = "BurnedArea")

If I try the same code in the terminal, everything works OK!

**Comment by cvitolo** [comment]
This is due to the 'ncl' tool to convert hdf4 to netcdf. If this dependecy could be somehow lifted, the usability of the package would improve.

Help/suggestions needed!

**Comment by alpha-oliveira** [comment]
In Windows I had a problem with that function even in the terminal. I think it could be solved adding 
`,mode="wb"` in the line 107:
`download.file(url = the_url, destfile = file.path(my_temp_dir, fname),
                    quiet = TRUE, cacheOK = TRUE, mode= "wb")`
Otherwise, the hdf5 downloaded file is not valid. I took the cue from [here](https://support.bioconductor.org/p/97311/).

**Comment by lvhengani** [comment]
I am having a problem of running `get_gfed4` using terminal. The error is shown below:

~~~R
BurnedAreas <- get_gfed4(start_date = "2003-01-01", end_date = "2015-12-31", temporal_resolution = "daily", varname = "BurnedArea", region = "GLOB")
Error in curl::curl_fetch_disk(url, x$path, handle = handle) :
Timeout was reached: Connection time-out
Either the data or the server are unavailable.
Error in get_gfed4(start_date = "2003-01-01", end_date = "2015-12-31",  :
Please check whether your dates are valid or try again later.
~~~ 

What could be causing this?

**Comment by Yicheng-Shen** [comment]
Downloading ftp://fuoco.geog.umd.edu/gfed4/monthly/GFED4.0_MQ_199701_BA.hdf
Error in function (type, msg, asError = TRUE)  : 
  Failed to connect to fuoco.geog.umd.edu port 21: Operation timed out
Error in get_gfed4(start_date = "1997-01-01", end_date = "2016-12-31",  : 
  Server currently unavailable, please try again later.

Why could it happen?

**Comment by cvitolo** [comment]
GFED ftp seems no longer working (http://globalfiredata.org/pages/data/#burned-area).
The function `get_gfed()` will be deprecated.

**Comment by cvitolo** [comment]
The function get_gfed() is now defunct.
